filenames:
  - /var/log_host/auth.log
  - /var/log_host/syslog
  - /var/log_host/kern.log
labels:
  type: syslog
---
filenames:
  - /var/log/traefik/logs/*.log
labels:
  type: traefik
---
filenames:
  - /var/log/jellyfin/config/log/log_*.log
labels:
  type: jellyfin
---
filenames:
  - /var/log/jellyseerr/config/logs/overseerr.log
labels:
  type: jellyseerr
---
filenames:
  - /var/log/nextcloud/logs/nextcloud.log
labels:
  type: nextcloud
---
filenames:
  - /var/log/nextcloud/logs/apache2/*.log
labels:
  type: apache2
---
filenames:
  - /var/log/vaultwarden/logs/vaultwarden.log
labels:
  type: vaultwarden
---
filenames:
  - /var/log/teamspeak/teamspeak/logs/ts3server_*.log
labels:
  type: ts3
---
source: docker
container_name:
 - authentik-server
labels:
  type: authentik
