services:
  gitea-server:
    image: gitea/gitea:latest
    container_name: gitea-server
    restart: always
    ports:
      - "3000:3000"
      - "2222:2222"
    volumes:
      - /home/git/.ssh
      - ./data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      LOCAL_ROOT_URL: $LOCAL_ROOT_URL
      GITEA__server__START_SSH_SERVER: true
      GITEA__server__SSH_PORT: 2222
      GITEA__server__SSH_LISTEN_PORT: 2222
      GITEA__database__DB_TYPE: postgres
      GITEA__database__HOST: gitea-db:5432
      GITEA__database__NAME: $GITEA_DB
      GITEA__database__USER: $GITEA_USER
      GITEA__database__PASSWD: $GITEA_USER_PW
    depends_on:
      - gitea-db

  gitea-db:
    image: postgres:14
    container_name: gitea-db
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: $GITEA_USER
      POSTGRES_PASSWORD: $GITEA_USER_PW
      POSTGRES_DB: $GITEA_DB

  gitea-runner:
    image: gitea/act_runner:latest
    container_name: gitea-runner
    restart: always
    environment:
      CONFIG_FILE: /config.yaml
      GITEA_INSTANCE_URL: gitea-server
      GITEA_RUNNER_REGISTRATION_TOKEN: $SELFHOSTED_RUNNER_TOKEN
      GITEA_RUNNER_NAME: $SELFHOSTED_RUNNER_NAME
      RUNNER_TOOL_CACHE: /toolcache
    volumes:
      - ./runner/config.yaml:/config.yaml
      - ./runner/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - gitea-server