name: Remove my public IP from Crowdsec
on:
  schedule:
    - cron: "*/20 * * * *"
  push:
    paths:
    - ".gitea/workflows/remove-myip-from-crowdsec.yml"

jobs:
  Kill Jellyfin Streams:
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-latest
      volumes:
        - /data:/opt/hostedtoolcache
    steps:
      - name: Install dependencies
        run: |
          echo "Check if dig is installed"
          if ! [ -x "$(command -v dig)" ]; then
            echo "Dig is not available, installing dnsutils"
            apt update -y && apt-get install -y --no-install-recommends dnsutils
          else
            echo "Dig is already available"
          fi
      - name: Remove my public IP from Crowdsec
        shell: bash
        run: |
          echo "Removing public IP from CrowdSec"
          domain="${{ vars.LOCAL_DOMAIN }}"
          ssh_user="${{ secrets.SSH_USER }}"
          host="rpi01"
          myip=$(dig +short txt ch whoami.cloudflare @1.0.0.1)
          if [ -n "$myip" ]; then
            declare -A HOSTS=( ["rpi01"]="${{ secrets.SSH_RPI01_PRIVATE_KEY }}" )
            echo "Add SSH key for '$host'"
            install -m 600 -D /dev/null ~/.ssh/id_rsa_$host_gitea_runner
            echo "${HOSTS[$host]}" > ~/.ssh/id_rsa_$host_gitea_runner
            (ssh-keyscan -H $host.$domain > ~/.ssh/known_hosts) 2> /dev/null
            echo "Remove public IP $myip from CrowdSec"
            crowdsec_answer=$(ssh -i ~/.ssh/id_rsa_$host_gitea_runner $ssh_user@$host.$domain "docker exec -t crowdsec cscli decisions delete -i $myip")
            if [[ $crowdsec_answer != *"0"* ]]; then
              echo "Public IP found and removed from CrowdSec DB:"
              echo $crowdsec_answer
            else
              echo "Public IP not found in CrowdSec DB"
            fi
          else
            echo "Public IP couldn't get determined"
          fi
      - name: Cleanup SSH credentials
        run: |
          echo "Cleanup SSH credentials"
          rm -f ~/.ssh/gitea