services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    volumes:
      - ./vaultwarden:/data/
      - ./logs:/var/log
    environment:
      SIGNUPS_ALLOWED: 'false'
      LOG_FILE: "/var/log/vaultwarden.log"
      LOG_LEVEL: "warn"
      ROCKET_CLI_COLORS: "false"
      EXTENDED_LOGGING: "true"
      IP_HEADER: "X-Forwarded-For"
    labels:
      traefik.enable: true
      traefik.http.routers.vaultwarden-rtr.entrypoints: https
      traefik.http.routers.vaultwarden-rtr.rule: Host(`$FQDN`)
      traefik.http.routers.vaultwarden-rtr.middlewares: chain-no-auth@file
      traefik.http.routers.vaultwarden-rtr.service: vaultwarden-svc
      traefik.http.services.vaultwarden-svc.loadbalancer.server.port: 80
    networks:
      - proxy

networks:
  proxy:
    external: true
