services:
  crowdsec:
    image: crowdsecurity/crowdsec:latest
    container_name: crowdsec
    hostname: $HOSTNAME
    restart: always
    security_opt:
      - no-new-privileges=true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config:/etc/crowdsec
      - ./data:/var/lib/crowdsec/data
      - /var/log:/var/log:ro
    environment:
      COLLECTIONS: "crowdsecurity/whitelist-good-actors"
      DISABLE_LOCAL_API: "true"
      AGENT_USERNAME: $HOSTNAME
      AGENT_PASSWORD: $CROWDSEC_AGENT_PASSWORD
      LOCAL_API_URL: http://$LOCAL_API_IP:8082