services:
  guacamole-db:
    image: postgres:16
    container_name: guacamole-db
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d:ro
    environment:
      TZ: $TZ
      POSTGRES_DB: $GUACAMOLE_DB
      POSTGRES_USER: $GUACAMOLE_DB_USER
      POSTGRES_PASSWORD: $GUACAMOLE_DB_USER_PW

  guacamole-guacd:
    image: guacamole/guacd:latest
    container_name: guacamole-guacd
    restart: always
    volumes:
    - ./drive:/drive
    - ./record:/var/lib/guacamole/recordings
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro

  guacamole:
    image: guacamole/guacamole:latest
    container_name: guacamole
    restart: always
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
    environment:
      GUACD_HOSTNAME: guacamole-guacd
      POSTGRESQL_HOSTNAME: guacamole-db
      POSTGRESQL_DATABASE: $GUACAMOLE_DB
      POSTGRESQL_USER: $GUACAMOLE_DB_USER
      POSTGRESQL_PASSWORD: $GUACAMOLE_DB_USER_PW
      POSTGRESQL_AUTO_CREATE_ACCOUNTS: true
      OPENID_AUTHORIZATION_ENDPOINT: $OPENID_AUTHORIZATION_ENDPOINT
      OPENID_CLIENT_ID: $OPENID_CLIENT_ID
      OPENID_ISSUER: $OPENID_ISSUER
      OPENID_JWKS_ENDPOINT: $OPENID_JWKS_ENDPOINT
      OPENID_REDIRECT_URI: https://$FQDN/
    labels:
      traefik.enable: true
      traefik.http.routers.guacamole-rtr.entrypoints: https
      traefik.http.routers.guacamole-rtr.rule: Host(`$FQDN`)
      traefik.http.middlewares.guacamole-mw-prefix.addprefix.prefix: /guacamole
      traefik.http.routers.guacamole-rtr.middlewares: chain-no-auth@file,guacamole-mw-prefix
      traefik.http.routers.guacamole-rtr.service: guacamole-svc
      traefik.http.services.guacamole-svc.loadbalancer.server.port: 8080
    networks:
      - proxy
      - default
    depends_on:
      - guacamole-db
      - guacamole-guacd

networks:
  proxy:
    external: true