services:
  deunhealth:
    build: .
    image: qmcgaw/deunhealth
    container_name: deunhealth
    restart: always
    network_mode: "none"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      LOG_LEVEL: info
      HEALTH_SERVER_ADDRESS: 127.0.0.1:9999
      TZ: $TZ