services:
  nextcloud-db:
    image: postgres:16
    container_name: nextcloud-db
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      TZ: $TZ
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PW
      POSTGRES_DB: $DB

  nextcloud-redis:
    image: redis:latest
    container_name: nextcloud-redis
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./redis:/data
    command: redis-server --appendonly yes --requirepass $REDIS_PW --maxmemory 512mb --maxmemory-policy allkeys-lru

  nextcloud:
    image: nextcloud:stable
    container_name: nextcloud
    hostname: nextcloud
    restart: always
    volumes:
      - ./nextcloud:/var/www/html
      - ./data:/var/www/html/data
      - ./logs:/var/log
    environment:
      TZ: $TZ
      REDIS_HOST: nextcloud-redis
      REDIS_HOST_PASSWORD: $REDIS_PW
      POSTGRES_HOST: nextcloud-db
      POSTGRES_DB: $DB
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PW
    labels:
      traefik.enable: true
      traefik.http.routers.nextcloud-rtr.entrypoints: https
      traefik.http.routers.nextcloud-rtr.rule: Host(`$NEXTCLOUD_HOST.$DOMAIN`)
      traefik.http.middlewares.middlewares-nextcloud-redirect.redirectregex.regex: ^/.well-known/(cal|card)dav
      traefik.http.middlewares.middlewares-nextcloud-redirect.redirectregex.replacement: /remote.php/dav/
      traefik.http.routers.nextcloud-rtr.middlewares: chain-no-auth@file,middlewares-nextcloud-redirect
      traefik.http.routers.nextcloud-rtr.service: nextcloud-svc
      traefik.http.services.nextcloud-svc.loadbalancer.server.port: 80
    depends_on:
      - nextcloud-redis
      - nextcloud-db
    networks:
      - proxy
      - default

  nextcloud-collabora:
    image: collabora/code:latest
    container_name: nextcloud-collabora
    restart: always
    environment:
      TZ: $TZ
      aliasgroup1: https://$NEXTCLOUD_HOST.$DOMAIN
      dictionaries: de_DE,en_US
      username: $COLLAB_USER
      password: $COLLAB_PW
      DONT_GEN_SSL_CERT: YES
      extra_params: --o:ssl.enable=false --o:ssl.termination=true
    labels:
      traefik.enable: true
      traefik.http.routers.collab-rtr.entrypoints: https
      traefik.http.routers.collab-rtr.rule: Host(`$COLLAB_HOST.$DOMAIN`)
      traefik.http.routers.collab-rtr.middlewares: chain-no-auth@file
      taefik.http.routers.collab-rtr.service: collab-svc
      traefik.http.services.collab-svc.loadbalancer.server.port: 9980
    networks:
      - proxy
      - default

networks:
  proxy:
    external: true
