services:
  minecraft:
    image: itzg/minecraft-server:latest
    container_name: minecraft
    restart: always
    tty: true
    stdin_open: true
    volumes:
      - ./data:/data
    environment:
      EULA: "TRUE"
      INIT_MEMORY: 1G
      MAX_MEMORY: 4G
      RCON_PASSWORD: $RCON_PASSWORD
    labels:
      traefik.enable: true
      traefik.tcp.routers.minecraft25565-rtr.entrypoints: minecraft25565
      traefik.tcp.routers.minecraft25565-rtr.rule: HostSNI(`*`)
      traefik.tcp.routers.minecraft25565-rtr.service: minecraft25565-svc
      traefik.tcp.services.minecraft25565-svc.loadbalancer.server.port: 25565
      traefik.tcp.routers.minecraft25575-rtr.entrypoints: minecraft25575
      traefik.tcp.routers.minecraft25575-rtr.rule: HostSNI(`*`)
      traefik.tcp.routers.minecraft25575-rtr.service: minecraft25575-svc
      traefik.tcp.services.minecraft25575-svc.loadbalancer.server.port: 25575
    networks:
      - proxy

networks:
  proxy:
    external: true
